@api_url = http://localhost:8080/api/books

### Add a new book
POST {{api_url}}
Content-Type: application/json

{
  "title": "The Hobbit",
  "metadata": {
    "author": "J.R.R. Tolkien",
    "genre": "Fantasy",
    "pages": 310
  }
}

### Add another book
POST {{api_url}}
Content-Type: application/json

{
  "title": "1984",
  "metadata": {
    "author": "George Orwell",
    "genre": "Dystopian",
    "published": 1949,
    "test2": "Test Pub"
  }
}

### Get all books
GET {{api_url}}

### Get metadata keys
GET {{api_url}}/metadata-keys

### Delete Book with id
DELETE {{api_url}}/695d68ca277172fe95de6ccd

### Update Book with id
PUT {{api_url}}/695e8ca5ce9efe4192a03558
Content-Type: application/json

{
  "title": "1984",
  "metadata": {
    "author": "George Orwell",
    "genre": "Dystopian",
    "published": 1949,
    "test2": "Test Pub"
  }
}

### Pagination
GET {{api_url}}/pages?size=1&page=2